# ruff: noqa
exc_type  # unused variable (deduplicate/llm/client.py:39)
tb  # unused variable (deduplicate/llm/client.py:39)
exc_type  # unused variable (deduplicate/logging_support.py:74)
tb  # unused variable (deduplicate/logging_support.py:74)
exc_tb  # unused variable (ie/client.py:56)
exc_type  # unused variable (ie/client.py:56)
exc_val  # unused variable (ie/client.py:56)
exc_tb  # unused variable (tests/test_ie_runner.py:75)
exc_type  # unused variable (tests/test_ie_runner.py:75)
exc_val  # unused variable (tests/test_ie_runner.py:75)
exc_tb  # unused variable (tests/test_ie_runner.py:102)
exc_type  # unused variable (tests/test_ie_runner.py:102)
exc_val  # unused variable (tests/test_ie_runner.py:102)
exc_tb  # unused variable (tests/test_ie_runner.py:134)
exc_type  # unused variable (tests/test_ie_runner.py:134)
exc_val  # unused variable (tests/test_ie_runner.py:134)
exc_tb  # unused variable (tests/test_ie_runner.py:158)
exc_type  # unused variable (tests/test_ie_runner.py:158)
exc_val  # unused variable (tests/test_ie_runner.py:158)
exc_tb  # unused variable (tests/test_ie_runner.py:187)
exc_type  # unused variable (tests/test_ie_runner.py:187)
exc_val  # unused variable (tests/test_ie_runner.py:187)
exc_tb  # unused variable (tests/test_ie_runner.py:212)
exc_type  # unused variable (tests/test_ie_runner.py:212)
exc_val  # unused variable (tests/test_ie_runner.py:212)
model_config  # vulture: pydantic config attribute
_.row_factory  # vulture: sqlite connection attribute
_.side_effect  # vulture: test mock attribute
_.__iter__  # vulture: test mock attribute
on_startup  # unused function (memory_agent/app.py:70)
retrieve_memories  # unused function (memory_agent/app.py:164)
retrieve_memories_debug  # unused function (memory_agent/app.py:202)
health  # unused function (memory_agent/app.py:225)
