"""Type stubs for datasketch library."""

class MinHash:
    """MinHash signature for estimating Jaccard similarity."""

    def __init__(self, num_perm: int = 128, seed: int = 1) -> None: ...
    def update(self, b: bytes) -> None: ...
    def jaccard(self, other: MinHash) -> float: ...
    def count(self) -> int: ...
    def merge(self, other: MinHash) -> None: ...
    def copy(self) -> MinHash: ...
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...

class MinHashLSH:
    """Locality Sensitive Hashing index for MinHash signatures."""

    def __init__(
        self,
        threshold: float = 0.5,
        num_perm: int = 128,
        weights: tuple[float, float] = (0.5, 0.5),
        params: tuple[int, int] | None = None,
    ) -> None: ...
    def insert(self, key: str, minhash: MinHash) -> None: ...
    def query(self, minhash: MinHash) -> list[str]: ...
    def remove(self, key: str) -> None: ...
    def is_empty(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
